version: "3.7"

services:
  go-main:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - auth-service
    command: ["./wait-for-it.sh", "postgres:5432", "--", "go", "run", "server_main.go"]

  auth-service:
    build: server
    ports:
      - 8081:8081
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "go", "run", "./cmd/auth/"]
  
  postgres:
    build: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    
