version: "3.7"

services:
  go-main:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - auth-service
    command: ["go", "run", "server_main.go"]
  
  auth-service:
    build: server
    # ports are not needed if we only communicate inside docker-compose network
    # ports:
    #   - 8081:8081
    command: ["go", "run", "./cmd/auth/"]

volumes:
  postgres-volume:
    
