version: "3.7"

services:
  go-main:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - user-service
      - auth-service
      - pins-service
      - comments-service
    command: ["go", "run", "server_main.go"]
  
  user-service:
    build: server
    ports:
      - 8082:8082
    command: ["go", "run", "./cmd/user/"]
  
  auth-service:
    build: server
    ports:
      - 8083:8083
    depends_on:
      - user-service
    command: ["go", "run", "./cmd/auth/"]

  pins-service:
    build: server
    ports:
      - 8084:8084
    depends_on:
      - user-service
    command: ["go", "run", "./cmd/pins/"]
  
  comments-service:
    build: server
    ports:
      - 8085:8085
    depends_on:
      - user-service
      - pins-service
    command: ["go", "run", "./cmd/comments/"]
    
