version: "3.7"

services:
  go-main:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - auth-service
      - user-service
    command: ["go", "run", "server_main.go"]
  
  auth-service:
    build: server
    # exposed ports are not needed if we only communicate inside docker-compose network
    # ports:
    #   - 8081:8081
    command: ["go", "run", "./cmd/auth/"]
  
  user-service:
    build: server
    # exposed ports are not needed if we only communicate inside docker-compose network
    # ports:
    #   - 8082:8082
    command: ["go", "run", "./cmd/user/"]
