global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
      - targets: ['go-main:8080']
    scheme: https
    tls_config:
      #ca_file: prometheus-example-ca-crt.pem
      cert_file: cert.pem
      key_file: key.pem

rule_files:
  - 'alerts.yml'
