name: Pinterest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Set up GolangCI-Lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $HOME/bin v1.27.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test with race detector
        run: |
          cd ./server
          ./run-tests.sh
